# Generated by Django 4.0.3 on 2022-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/abc.jpeg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
