# Generated by Django 4.0.3 on 2022-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/abc.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
