# Generated by Django 4.0.3 on 2022-03-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_course_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Abc',
        ),
    ]
