# Generated by Django 4.0.3 on 2022-03-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_tag_abc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abc',
            new_name='Tag',
        ),
    ]
