# Generated by Django 4.0.3 on 2022-03-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_abc_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
